sudo: required
services:
  - docker

before_install:
  - docker build -t mrhassanmurtaza/docker-react-cicd-demo -f Dockerfile.dev .

script: 
  - docker run -e CI=true mrhassanmurtaza/docker-react-cicd-demo npm run test
